app = "vidur-agent"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  LOG_FORMAT = "json"

[processes]
  worker = "python -m agent.worker start"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
